/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empresa_gui;

import empresa_gui.DialogEmpresa;
import empresa_gui.DialogListaEmpresas;
import empresa_model.Empresa;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import empresa_model.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author cancian
 */
public class FramePrincipal extends javax.swing.JFrame {

    
    private DefaultListModel<String> empresaListModel;
    private JList<String> empresaList;
 

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
            initComponents();
    } 
    

    
    public void addEmpresaToList(Empresa empresa) {
    empresaListModel.addElement(empresa.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoNovo = new javax.swing.JMenuItem();
        menuArquivoAbrir = new javax.swing.JMenuItem();
        menuArquivoSalvar = new javax.swing.JMenuItem();
        menuArquivoFechar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuEmpresa = new javax.swing.JMenu();
        menuEmpresaEditar = new javax.swing.JMenuItem();
        menuEmpresaListar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuSetor = new javax.swing.JMenu();
        menuSetorNovo = new javax.swing.JMenuItem();
        menuSetorEditar = new javax.swing.JMenuItem();
        menuSetorListar = new javax.swing.JMenuItem();
        menuColaborador = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Empresas");
        setMinimumSize(new java.awt.Dimension(300, 300));

        menuArquivo.setText("Arquivo");

        menuArquivoNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuArquivoNovo.setText("Novo Arquivo");
        menuArquivoNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuArquivoNovoMouseClicked(evt);
            }
        });
        menuArquivoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoNovoActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoNovo);

        menuArquivoAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuArquivoAbrir.setText("Abrir");
        menuArquivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoAbrirActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoAbrir);

        menuArquivoSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuArquivoSalvar.setText("Salvar");
        menuArquivoSalvar.setEnabled(false);
        menuArquivoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSalvarActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoSalvar);

        menuArquivoFechar.setText("Fechar");
        menuArquivoFechar.setEnabled(false);
        menuArquivoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoFecharActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoFechar);
        menuArquivo.add(jSeparator1);

        menuArquivoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuArquivoSair.setText("Sair");
        menuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoSair);

        jMenuBar1.add(menuArquivo);

        menuEmpresa.setText("Empresa");

        menuEmpresaEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuEmpresaEditar.setText("Editar");
        menuEmpresaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresaEditarActionPerformed(evt);
            }
        });
        menuEmpresa.add(menuEmpresaEditar);

        menuEmpresaListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuEmpresaListar.setText("Listar");
        menuEmpresaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresaListarActionPerformed(evt);
            }
        });
        menuEmpresa.add(menuEmpresaListar);
        menuEmpresa.add(jSeparator2);

        menuSetor.setText("Setor");

        menuSetorNovo.setText("Novo");
        menuSetor.add(menuSetorNovo);

        menuSetorEditar.setText("Editar");
        menuSetor.add(menuSetorEditar);

        menuSetorListar.setText("Listar");
        menuSetor.add(menuSetorListar);

        menuEmpresa.add(menuSetor);

        jMenuBar1.add(menuEmpresa);

        menuColaborador.setText("Colaborador");
        menuColaborador.setEnabled(false);
        jMenuBar1.add(menuColaborador);

        jMenu1.setText("...");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void menuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSairActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Sair do Sistema", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuArquivoSairActionPerformed

    private void menuEmpresaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresaEditarActionPerformed
        // TODO add your handling code here:
        DialogEmpresa form = new DialogEmpresa(this, true);
        form.setModel(empresaAtual);
        form.setVisible(true);
        // a janela de diálogo modal foi escondida
        Empresa retorno = form.getModalResult();
        if (retorno != null) {
            empresaAtual = retorno;
        }
        AtualizaMenus(); // não é bom o mesmo código aparecer em muitos lugares
    }//GEN-LAST:event_menuEmpresaEditarActionPerformed

    private void menuEmpresaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresaListarActionPerformed
        // TODO add your handling code here:
        DialogListaEmpresas form = new DialogListaEmpresas(this, true);
        form.setModel(empresas);
        form.setVisible(true);
    }//GEN-LAST:event_menuEmpresaListarActionPerformed

    private void menuArquivoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoNovoActionPerformed
        // TODO add your handling code here:
              // Create an instance of DialogListaEmpresas
        DialogEmpresa dialog = new DialogEmpresa(this, true);
        dialog.setVisible(true); // Show the dialog

        Empresa retorno = dialog.getModalResult();
        if (retorno != null) {
            empresas.add(retorno);
        }
    
        //...
        // use JFileChooser (seção 15.6) para permitir que o usuário crie um novo arquivo para conter informações das empresas 
        // ...
        // arquivoAtual = fileChooser.getSelectedFile();
        // ...
        AtualizaMenus(); // não é bom o mesmo código aparecer em muitos lugares
    }//GEN-LAST:event_menuArquivoNovoActionPerformed

    private void menuArquivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoAbrirActionPerformed
   /*    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Abrir arquivo de empresa");
    fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos serializados", "ser"));

    int userSelection = fileChooser.showOpenDialog(this);
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try {
            Empresa empresa = EmpresaDeserializer.deserializeEmpresa(file);
            DialogEmpresa dialog = new DialogEmpresa(this, true, empresa);  // cannot be applied to given types, required Frame, boolean
            dialog.setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(DialogEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo de empresa: " + ex.getMessage());
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(DialogEmpresa.class.getName()).log(Level.WARNING, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }*/
        AtualizaMenus(); // não é bom o mesmo código aparecer em muitos lugares
    }//GEN-LAST:event_menuArquivoAbrirActionPerformed

    private void menuArquivoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSalvarActionPerformed
        // TODO add your handling code here:
        //...
        // use JFileChooser (seção 15.6) para permitir que o usuário escolha um arquivo para salvar as empresas (se um arquivo já estiver definido, ele deve aparecer selecionado)
        //String nomeEscolhido = 
        //...
        // serializa os objetos e salva empresas no arquivo
        //...

        // this.nomeArquivoAtual = nomeEscolhido;
        //
        AtualizaMenus(); // não é bom o mesmo código aparecer em muitos lugares
    }//GEN-LAST:event_menuArquivoSalvarActionPerformed

    private void menuArquivoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoFecharActionPerformed
        // TODO add your handling code here:
        //...
        // poderia verificar se houve alguma alteração nos dados e, se houve, perguntar antes de fechar o arquivo

        arquivoAtual = null;
        AtualizaMenus(); // não é bom o mesmo código aparecer em muitos lugares
    }//GEN-LAST:event_menuArquivoFecharActionPerformed

    private void menuArquivoNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuArquivoNovoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArquivoNovoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    private void AtualizaMenus() {
        boolean arquivoNovoOuAberto = arquivoAtual != null;
        menuEmpresa.setEnabled(arquivoNovoOuAberto);
        menuColaborador.setEnabled(arquivoNovoOuAberto);
        menuEmpresaEditar.setEnabled(empresaAtual != null);
        menuArquivoFechar.setEnabled(arquivoNovoOuAberto);
        menuArquivoSalvar.setEnabled(arquivoNovoOuAberto);

        if (!arquivoNovoOuAberto) {
            this.setTitle("Gerenciador de Empresas");
        } else {
            this.setTitle("Gerenciador de Empresas {"+arquivoAtual.getName()+"}");

        }
    }

    private Empresa empresaAtual;
    private final ArrayList<Empresa> empresas = new ArrayList<>();
    private File arquivoAtual;
    //private boolean algumaALteracao = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoAbrir;
    private javax.swing.JMenuItem menuArquivoFechar;
    private javax.swing.JMenuItem menuArquivoNovo;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenuItem menuArquivoSalvar;
    private javax.swing.JMenu menuColaborador;
    private javax.swing.JMenu menuEmpresa;
    private javax.swing.JMenuItem menuEmpresaEditar;
    private javax.swing.JMenuItem menuEmpresaListar;
    private javax.swing.JMenu menuSetor;
    private javax.swing.JMenuItem menuSetorEditar;
    private javax.swing.JMenuItem menuSetorListar;
    private javax.swing.JMenuItem menuSetorNovo;
    // End of variables declaration//GEN-END:variables


}

